cookie:
  expiry_days: 90
  key: deadpool-app
  name: deadpool-app-authenticated
credentials:
  usernames:
    alexander.g.obrien@gmail.com:
      id: c6729ac9-4245-4a23-85bb-d3f027a3d4e9
      email: alexander.g.obrien@gmail.com
      failed_login_attempts: 0
      first_name: Alexander
      last_name: O'Brien
      logged_in: false
      password: $2b$12$01XhsneBMWwZ/G1ykOUy7OOb5Kbe/hy8wAkvbjVzrC/tZp9E0vJj6
      roles:
      - user
    broepke@gmail.com:
      id: 1831699b-e255-45ff-8671-b5c840922735
      email: broepke@gmail.com
      failed_login_attempts: 0
      first_name: Brian
      last_name: Roepke
      logged_in: false
      password: $2b$12$CI2MOIAFgb/XBD9laECG8Omaf75WV3CVRVCwHc/CBqzkyTLdK.STy
      roles:
      - admin
      - user
    bschanen@gmail.com:
      id: aecdf4a2-0bad-4c96-89ca-82385a6f6ee0
      email: bschanen@gmail.com
      failed_login_attempts: 0
      first_name: Brian
      last_name: Schanen
      logged_in: false
      password: $2b$12$YdyBoi3DNNsKSCUSREaBNe39SVeK/e6Aa6XCVW4hJ8GH6LWEk7NVK
      roles:
      - user
    cgroepke2@gmail.com:
      id: d0c9e165-0881-4e1a-b397-75520e8219b3
      email: cgroepke2@gmail.com
      failed_login_attempts: 0
      first_name: Chrissy
      last_name: Roepke
      logged_in: false
      password: $2b$12$8UqzhcGvIaPUnjB/cRgw9OVqBpaqPWOASZkXw/bztW7CgfJjH8RwK
      roles:
      - user
    christopherpvienneau@gmail.com:
      id: b63187cf-4a15-4f70-9906-2686f2c6b835
      email: christopherpvienneau@gmail.com
      failed_login_attempts: 0
      first_name: Chris
      last_name: Vienneau
      logged_in: false
      password: $2b$12$Vmz6ocqB5dm/A3Km4fuKjOKRiTS/T4ko3qd7FnymWKTZxtC0eMFea
      roles:
      - admin
      - user
    clm1970@gmail.com:
      id: a6d5a84a-b8e2-47cc-8af1-cb5b02593d6d
      email: clm1970@gmail.com
      failed_login_attempts: 0
      first_name: Luke
      last_name: Marble
      logged_in: false
      password: $2b$12$gEDIb.j3fv5skQKpIFegJOZii54QrJKWCFlQhoIyOk3E.2brkdiQ.
      roles:
      - user
    derek.cornwall@wtwco.com:
      id: 0702751f-cb30-42d7-81d3-025b32f8dca0
      email: derek.cornwall@wtwco.com
      failed_login_attempts: 0
      first_name: Derek
      last_name: Cornwall
      logged_in: false
      password: $2b$12$X.Q2QO8qjNenjN.Fss2iZO1pzm0ea8I94P/PtI9TPzQ7VsL2/kHGa
      roles:
      - user
    frazierandrewd@gmail.com:
      id: bc913bed-5795-441d-916b-2a778383858e
      email: frazierandrewd@gmail.com
      failed_login_attempts: 0
      first_name: Andrew
      last_name: Frazier
      logged_in: false
      password: $2b$12$HVjIloNQsmIj.uTRmBXkqefGQjb8/NQsJ/aawOgKngaDwOACKl5s.
      roles:
      - user
    jahnwarren@gmail.com:
      id: 3fe9975d-7516-4b86-9edc-f90448424819
      email: jahnwarren@gmail.com
      failed_login_attempts: 0
      first_name: Warren
      last_name: Jahn
      logged_in: false
      password: $2b$12$BaQwLzEiMCb6yZhaLMDd6epXaeV8nBN6JXxD4RAj0uULaCd6gaiRq
      roles:
      - user
    lwelch15@gmail.com:
      id: adaf41a2-d0f6-44ae-96df-1693e02e88d6
      email: lwelch15@gmail.com
      failed_login_attempts: 0
      first_name: Loren
      last_name: Welch
      logged_in: false
      password: $2b$12$6V3rfa3lcpBwhvY5uyCj3ukoiOYQULNp10kn0xQhdNrl0WaIu1dCa
      roles:
      - user
    rjkennedy1260@gmail.com:
      id: 1769888a-8594-4fad-a95b-553d7fa1a897
      email: rjkennedy1260@gmail.com
      failed_login_attempts: 0
      first_name: Robert
      last_name: Kennedy
      logged_in: false
      password: $2b$12$o8b/ljga/s7YRppGpslv8e1CgXMZeVMie5iGI5dhMDlw54qWfSsBG
      roles:
      - user
    smohs1@hotmail.com:
      id: 3a3282d1-dfda-477f-a8e5-4f7fa474c37a
      email: smohs1@hotmail.com
      failed_login_attempts: 0
      first_name: Steve
      last_name: Mohs
      logged_in: false
      password: $2b$12$4TfNtdCk4V3nNMe5ScaYJeu1x3xAjS/k2HleVAue5KkOXCfV53EDO
      roles:
      - user
    thepromodepot@gmail.com:
      id: 0f7bc0ea-6704-491d-8fe0-5a015a9851c9
      email: thepromodepot@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Wholihan
      logged_in: false
      password: $2b$12$0gQldRnQDm7QFOC0X3FMmeUgJuFyOVWnWDlEVn/Ok4iasjbtVY9NO
      roles:
      - user
    willcokeley@gmail.com:
      id: 74c6942d-3a94-42f2-bed1-1457483d9eaa
      email: willcokeley@gmail.com
      failed_login_attempts: 0
      first_name: Will
      last_name: Cokeley
      logged_in: false
      password: $2b$12$Fr5LkfQ/FYkjVkTnfcvxoeRHZEGE9YyAYqCLDk2DO7nIy7qWdZZO.
      roles:
      - user
