cookie:
  expiry_days: 90
  key: deadpool-app
  name: deadpool_authenticated
credentials:
  usernames:
    alexander.g.obrien@gmail.com:
      email: alexander.g.obrien@gmail.com
      failed_login_attempts: 0
      first_name: Alexander
      last_name: O'Brien
      logged_in: false
      password: $2b$12$01XhsneBMWwZ/G1ykOUy7OOb5Kbe/hy8wAkvbjVzrC/tZp9E0vJj6
    broepke@gmail.com:
      email: broepke@gmail.com
      failed_login_attempts: 0
      first_name: Brian
      last_name: Roepke
      logged_in: false
      password: $2b$12$CI2MOIAFgb/XBD9laECG8Omaf75WV3CVRVCwHc/CBqzkyTLdK.STy
    bschanen@gmail.com:
      email: bschanen@gmail.com
      failed_login_attempts: 0
      first_name: Brian
      last_name: Schanen
      logged_in: false
      password: $2b$12$YdyBoi3DNNsKSCUSREaBNe39SVeK/e6Aa6XCVW4hJ8GH6LWEk7NVK
    cgroepke2@gmail.com:
      email: cgroepke2@gmail.com
      failed_login_attempts: 0
      first_name: Chrissy
      last_name: Roepke
      logged_in: false
      password: $2b$12$8UqzhcGvIaPUnjB/cRgw9OVqBpaqPWOASZkXw/bztW7CgfJjH8RwK
    christopherpvienneau@gmail.com:
      email: christopherpvienneau@gmail.com
      failed_login_attempts: 0
      first_name: Chris
      last_name: Vienneau
      logged_in: false
      password: $2b$12$Vmz6ocqB5dm/A3Km4fuKjOKRiTS/T4ko3qd7FnymWKTZxtC0eMFea
    clm1970@gmail.com:
      email: clm1970@gmail.com
      failed_login_attempts: 0
      first_name: Luke
      last_name: Marble
      logged_in: false
      password: $2b$12$gEDIb.j3fv5skQKpIFegJOZii54QrJKWCFlQhoIyOk3E.2brkdiQ.
    derek.cornwall@wtwco.com:
      email: derek.cornwall@wtwco.com
      failed_login_attempts: 0
      first_name: Derek
      last_name: Cornwall
      logged_in: false
      password: $2b$12$X.Q2QO8qjNenjN.Fss2iZO1pzm0ea8I94P/PtI9TPzQ7VsL2/kHGa
    frazierandrewd@gmail.com:
      email: frazierandrewd@gmail.com
      failed_login_attempts: 0
      first_name: Andrew
      last_name: Frazier
      logged_in: false
      password: $2b$12$HVjIloNQsmIj.uTRmBXkqefGQjb8/NQsJ/aawOgKngaDwOACKl5s.
    jahnwarren@gmail.com:
      email: jahnwarren@gmail.com
      failed_login_attempts: 0
      first_name: Warren
      last_name: Jahn
      logged_in: false
      password: $2b$12$BaQwLzEiMCb6yZhaLMDd6epXaeV8nBN6JXxD4RAj0uULaCd6gaiRq
    lwelch15@gmail.com:
      email: lwelch15@gmail.com
      failed_login_attempts: 0
      first_name: Loren
      last_name: Welch
      logged_in: false
      password: $2b$12$6V3rfa3lcpBwhvY5uyCj3ukoiOYQULNp10kn0xQhdNrl0WaIu1dCa
    rjkennedy1260@gmail.com:
      email: rjkennedy1260@gmail.com
      failed_login_attempts: 0
      first_name: Robert
      last_name: Kennedy
      logged_in: false
      password: $2b$12$o8b/ljga/s7YRppGpslv8e1CgXMZeVMie5iGI5dhMDlw54qWfSsBG
    smohs1@hotmail.com:
      email: smohs1@hotmail.com
      failed_login_attempts: 0
      first_name: Steve
      last_name: Mohs
      logged_in: false
      password: $2b$12$4TfNtdCk4V3nNMe5ScaYJeu1x3xAjS/k2HleVAue5KkOXCfV53EDO
    thepromodepot@gmail.com:
      email: thepromodepot@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Wholihan
      logged_in: false
      password: $2b$12$0gQldRnQDm7QFOC0X3FMmeUgJuFyOVWnWDlEVn/Ok4iasjbtVY9NO
    willcokeley@gmail.com:
      email: willcokeley@gmail.com
      failed_login_attempts: 0
      first_name: Will
      last_name: Cokeley
      logged_in: false
      password: $2b$12$Fr5LkfQ/FYkjVkTnfcvxoeRHZEGE9YyAYqCLDk2DO7nIy7qWdZZO.
